import fs from 'fs';
import path from 'path';

interface SwaggerDoc {
  paths: Record<string, Record<string, any>>;
  components?: {
    schemas?: Record<string, any>;
  };
}

function loadSwagger(path: string): SwaggerDoc {
  const content = fs.readFileSync(path, 'utf-8');
  return JSON.parse(content);
}

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]/g, '_')
    .split('_')
    .map(s => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase())
    .join('');
}

function toCamelCase(str: string): string {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function getResponseType(spec: any): string {
  const responses = spec.responses || {};
  const ok = responses['200'];
  if (!ok || !ok.content) return 'any';
  const json = ok.content['application/json'];
  if (!json || !json.schema) return 'any';
  const schema = json.schema;
  if (schema.$ref) {
    const ref = schema.$ref.split('/').pop();
    return ref ? `components["schemas"]["${ref}"]` : 'any';
  }
  if (schema.type === 'array' && schema.items) {
    if (schema.items.$ref) {
      const ref = schema.items.$ref.split('/').pop();
      return ref ? `components["schemas"]["${ref}"][]` : 'any[]';
    }
    return 'any[]';
  }
  return 'any';
}

function getRequestBodyType(spec: any): string | null {
  if (!spec.requestBody || !spec.requestBody.content) return null;
  const json = spec.requestBody.content['application/json'];
  if (!json || !json.schema) return null;
  const schema = json.schema;
  if (schema.$ref) {
    return schema.$ref.split('/').pop() || null;
  }
  return null;
}

function generateClient(): string {
  return `// Auto-generated by generate-openapi.ts
// Do not edit manually

export interface ClientConfig {
  apiHost?: string;
  apiKey?: string;
  getApiHost?: () => string | undefined;
  getApiKey?: () => string | undefined;
}

function getEnvVar(key: string): string | undefined {
  try {
    if (typeof process !== 'undefined' && process.env) {
      return process.env[key];
    }
  } catch {
    // ignore
  }
  try {
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    if (typeof import.meta !== 'undefined' && import.meta.env) {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      return import.meta.env[key] || import.meta.env[\`VITE_\${key}\`];
    }
  } catch {
    // ignore
  }
  return undefined;
}

const defaultGetApiHost = () => getEnvVar('TIER0_API_HOST');
const defaultGetApiKey = () => getEnvVar('TIER0_API_KEY');

class HttpClient {
  private config: ClientConfig;

  constructor(config: ClientConfig = {}) {
    this.config = config;
  }

  private getBaseURL(): string {
    const host = this.config.apiHost || this.config.getApiHost?.() || defaultGetApiHost();
    if (!host) {
      throw new Error('Tier0 SDK: apiHost is required. Set it via ClientConfig or TIER0_API_HOST environment variable.');
    }
    return \`http://\${host}\`;
  }

  private getApiKey(): string | undefined {
    return this.config.apiKey || this.config.getApiKey?.() || defaultGetApiKey();
  }

  private async request<T>(method: string, path: string, body?: any): Promise<T> {
    const baseURL = this.getBaseURL();
    const url = \`\${baseURL}\${path}\`;
    const apiKey = this.getApiKey();

    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };

    if (apiKey) {
      headers['Authorization'] = \`Bearer \${apiKey}\`;
    }

    const response = await fetch(url, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const text = await response.text().catch(() => 'Unknown error');
      throw new Error(\`HTTP \${response.status}: \${text}\`);
    }

    if (response.status === 204) {
      return undefined as T;
    }

    return response.json() as Promise<T>;
  }

  async get<T>(path: string): Promise<T> {
    return this.request<T>('GET', path);
  }

  async post<T>(path: string, body: any): Promise<T> {
    return this.request<T>('POST', path, body);
  }

  async put<T>(path: string, body: any): Promise<T> {
    return this.request<T>('PUT', path, body);
  }

  async patch<T>(path: string, body: any): Promise<T> {
    return this.request<T>('PATCH', path, body);
  }

  async delete<T>(path: string, body?: any): Promise<T> {
    return this.request<T>('DELETE', path, body);
  }
}

let defaultClient = new HttpClient();

export function configureClient(config: ClientConfig): void {
  defaultClient = new HttpClient(config);
}

export function getClient(): HttpClient {
  return defaultClient;
}

export { HttpClient };
`;
}

function generateApi(swagger: SwaggerDoc): string {
  const paths = swagger.paths || {};
  const modules: Record<string, Array<{ name: string; method: string; path: string; bodyType: string | null; responseType: string }>> = {};

  for (const [pathStr, methods] of Object.entries(paths)) {
    for (const [method, spec] of Object.entries(methods)) {
      const opId = spec.operationId || '';
      if (!opId) continue;

      let module = 'common';
      if (pathStr.includes('/flow/')) module = 'flow';
      else if (pathStr.includes('/uns/')) module = 'uns';
      else if (pathStr.includes('/auth/')) module = 'system';
      else if (pathStr.includes('/info')) module = 'system';
      else if (pathStr.includes('/reload')) module = 'system';

      if (!modules[module]) modules[module] = [];

      const bodyType = getRequestBodyType(spec);
      const responseType = getResponseType(spec);

      let fnName = opId;
      if (fnName.startsWith('get')) fnName = fnName.slice(3);
      else if (fnName.startsWith('post')) fnName = fnName.slice(4);
      else if (fnName.startsWith('put')) fnName = fnName.slice(3);
      else if (fnName.startsWith('patch')) fnName = fnName.slice(5);
      else if (fnName.startsWith('delete')) fnName = fnName.slice(6);

      fnName = toCamelCase(fnName);

      modules[module].push({
        name: fnName,
        method: method.toLowerCase(),
        path: pathStr,
        bodyType,
        responseType,
      });
    }
  }

  let code = `// Auto-generated by generate-openapi.ts\n// Do not edit manually\n\n`;
  code += `import { getClient } from './client.js';\n`;
  code += `import type { components } from './types.js';\n\n`;

  for (const [moduleName, fns] of Object.entries(modules)) {
    const apiName = `${moduleName}Api`;
    code += `export const ${apiName} = {\n`;

    for (const fn of fns) {
      const needsBody = fn.method === 'post' || fn.method === 'put' || fn.method === 'patch';
      const args = fn.bodyType ? `body: components["schemas"]["${fn.bodyType}"]` : (needsBody ? 'body?: any' : '');
      const bodyArg = fn.bodyType ? ', body' : (needsBody ? ', body' : '');
      const respType = fn.responseType === 'any' ? 'any' : fn.responseType;
      code += `  ${fn.name}: (${args}) => getClient().${fn.method}<${respType}>('${fn.path}'${bodyArg}),\n`;
    }

    code += `};\n\n`;
  }

  return code;
}

function generateReact(swagger: SwaggerDoc): string {
  const paths = swagger.paths || {};
  const modules: Record<string, Array<{ name: string; method: string; bodyType: string | null; responseType: string }>> = {};

  for (const [pathStr, methods] of Object.entries(paths)) {
    for (const [method, spec] of Object.entries(methods)) {
      const opId = spec.operationId || '';
      if (!opId) continue;

      let module = 'common';
      if (pathStr.includes('/flow/')) module = 'flow';
      else if (pathStr.includes('/uns/')) module = 'uns';
      else if (pathStr.includes('/auth/')) module = 'system';
      else if (pathStr.includes('/info')) module = 'system';
      else if (pathStr.includes('/reload')) module = 'system';

      if (!modules[module]) modules[module] = [];

      const bodyType = getRequestBodyType(spec);
      const responseType = getResponseType(spec);

      let fnName = opId;
      if (fnName.startsWith('get')) fnName = fnName.slice(3);
      else if (fnName.startsWith('post')) fnName = fnName.slice(4);
      else if (fnName.startsWith('put')) fnName = fnName.slice(3);
      else if (fnName.startsWith('patch')) fnName = fnName.slice(5);
      else if (fnName.startsWith('delete')) fnName = fnName.slice(6);
      fnName = toCamelCase(fnName);

      modules[module].push({
        name: fnName,
        method: method.toLowerCase(),
        bodyType,
        responseType,
      });
    }
  }

  let code = `// Auto-generated by generate-openapi.ts\n// Do not edit manually\n\n`;
  code += `// React hooks require @tanstack/react-query to be installed\n`;
  code += `import { useMutation } from '@tanstack/react-query';\n`;
  code += `import { ${Object.keys(modules).map(m => `${m}Api`).join(', ')} } from './api.js';\n`;
  code += `import type { components } from './types.js';\n\n`;

  for (const [moduleName, fns] of Object.entries(modules)) {
    const apiName = `${moduleName}Api`;
    for (const fn of fns) {
      const hookName = `use${toPascalCase(fn.name)}`;
      const bodyType = fn.bodyType ? `components["schemas"]["${fn.bodyType}"]` : 'void';
      const respType = fn.responseType === 'any' ? 'any' : fn.responseType;
      code += `export function ${hookName}() {\n`;
      code += `  return useMutation<${respType}, Error, ${bodyType}>({\n`;
      code += `    mutationFn: ${apiName}.${fn.name},\n`;
      code += `  });\n`;
      code += `}\n\n`;
    }
  }

  return code;
}

function generateVue(swagger: SwaggerDoc): string {
  const paths = swagger.paths || {};
  const modules: Record<string, Array<{ name: string; method: string; bodyType: string | null; responseType: string }>> = {};

  for (const [pathStr, methods] of Object.entries(paths)) {
    for (const [method, spec] of Object.entries(methods)) {
      const opId = spec.operationId || '';
      if (!opId) continue;

      let module = 'common';
      if (pathStr.includes('/flow/')) module = 'flow';
      else if (pathStr.includes('/uns/')) module = 'uns';
      else if (pathStr.includes('/auth/')) module = 'system';
      else if (pathStr.includes('/info')) module = 'system';
      else if (pathStr.includes('/reload')) module = 'system';

      if (!modules[module]) modules[module] = [];

      const bodyType = getRequestBodyType(spec);
      const responseType = getResponseType(spec);

      let fnName = opId;
      if (fnName.startsWith('get')) fnName = fnName.slice(3);
      else if (fnName.startsWith('post')) fnName = fnName.slice(4);
      else if (fnName.startsWith('put')) fnName = fnName.slice(3);
      else if (fnName.startsWith('patch')) fnName = fnName.slice(5);
      else if (fnName.startsWith('delete')) fnName = fnName.slice(6);
      fnName = toCamelCase(fnName);

      modules[module].push({
        name: fnName,
        method: method.toLowerCase(),
        bodyType,
        responseType,
      });
    }
  }

  let code = `// Auto-generated by generate-openapi.ts\n// Do not edit manually\n\n`;
  code += `// Vue composables require vue to be installed\n`;
  code += `import { ref } from 'vue';\n`;
  code += `import { ${Object.keys(modules).map(m => `${m}Api`).join(', ')} } from './api.js';\n`;
  code += `import type { components } from './types.js';\n\n`;

  for (const [moduleName, fns] of Object.entries(modules)) {
    const apiName = `${moduleName}Api`;
    for (const fn of fns) {
      const hookName = `use${toPascalCase(fn.name)}`;
      const hasBody = !!fn.bodyType;
      const bodyType = hasBody ? `components["schemas"]["${fn.bodyType}"]` : 'void';
      const respType = fn.responseType === 'any' ? 'any' : fn.responseType;
      code += `export function ${hookName}() {\n`;
      code += `  const data = ref<${respType} | null>(null);\n`;
      code += `  const loading = ref(false);\n`;
      code += `  const error = ref<Error | null>(null);\n\n`;
      if (hasBody) {
        code += `  const execute = async (body: ${bodyType}) => {\n`;
      } else {
        code += `  const execute = async () => {\n`;
      }
      code += `    loading.value = true;\n`;
      code += `    error.value = null;\n`;
      code += `    try {\n`;
      if (hasBody) {
        code += `      data.value = await ${apiName}.${fn.name}(body);\n`;
      } else {
        code += `      data.value = await ${apiName}.${fn.name}();\n`;
      }
      code += `      return data.value;\n`;
      code += `    } catch (e) {\n`;
      code += `      error.value = e as Error;\n`;
      code += `      throw e;\n`;
      code += `    } finally {\n`;
      code += `      loading.value = false;\n`;
      code += `    }\n`;
      code += `  };\n\n`;
      code += `  return { data, loading, error, execute };\n`;
      code += `}\n\n`;
    }
  }

  return code;
}

function generateIndex(): string {
  return `// Auto-generated by generate-openapi.ts\n// Do not edit manually\n\n` +
    `export * from './client.js';\n` +
    `export * from './api.js';\n` +
    `export type { components } from './types.js';\n`;
}

function main() {
  const args = process.argv.slice(2);
  let swaggerPath = '';
  let outputDir = '';

  for (let i = 0; i < args.length; i += 2) {
    if (args[i] === '--swagger') swaggerPath = args[i + 1];
    if (args[i] === '--output') outputDir = args[i + 1];
  }

  if (!swaggerPath || !outputDir) {
    console.error('Usage: tsx generate-openapi.ts --swagger <path> --output <dir>');
    process.exit(1);
  }

  const swagger = loadSwagger(swaggerPath);

  // Ensure output directory exists
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write generated files
  fs.writeFileSync(path.join(outputDir, 'client.ts'), generateClient(), 'utf-8');
  fs.writeFileSync(path.join(outputDir, 'api.ts'), generateApi(swagger), 'utf-8');
  fs.writeFileSync(path.join(outputDir, 'react.ts'), generateReact(swagger), 'utf-8');
  fs.writeFileSync(path.join(outputDir, 'vue.ts'), generateVue(swagger), 'utf-8');
  fs.writeFileSync(path.join(outputDir, 'index.ts'), generateIndex(), 'utf-8');

  console.log(`Generated OpenAPI SDK files in ${outputDir}`);
}

main();
