// Auto-generated by generate-openapi.ts
// Do not edit manually

export interface ClientConfig {
  baseURL?: string;
  apiKey?: string;
  getApiKey?: () => string | undefined;
  getBaseURL?: () => string | undefined;
}

function getEnvVar(key: string): string | undefined {
  try {
    if (typeof process !== 'undefined' && process.env) {
      return process.env[key];
    }
  } catch {
    // ignore
  }
  try {
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    if (typeof import.meta !== 'undefined' && import.meta.env) {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      return import.meta.env[key] || import.meta.env[`VITE_${key}`];
    }
  } catch {
    // ignore
  }
  return undefined;
}

const defaultGetApiKey = () => getEnvVar('TIER0_API_KEY');
const defaultGetBaseURL = () => getEnvVar('TIER0_BASE_URL');

class HttpClient {
  private config: ClientConfig;

  constructor(config: ClientConfig = {}) {
    this.config = config;
  }

  private getBaseURL(): string {
    const url = this.config.baseURL || this.config.getBaseURL?.() || defaultGetBaseURL();
    if (!url) {
      throw new Error('Tier0 SDK: baseURL is required. Set it via ClientConfig or TIER0_BASE_URL environment variable.');
    }
    return url.replace(/\/$/, '');
  }

  private getApiKey(): string | undefined {
    return this.config.apiKey || this.config.getApiKey?.() || defaultGetApiKey();
  }

  private async request<T>(method: string, path: string, body?: any): Promise<T> {
    const baseURL = this.getBaseURL();
    const url = `${baseURL}${path}`;
    const apiKey = this.getApiKey();

    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };

    if (apiKey) {
      headers['Authorization'] = `Bearer ${apiKey}`;
    }

    const response = await fetch(url, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const text = await response.text().catch(() => 'Unknown error');
      throw new Error(`HTTP ${response.status}: ${text}`);
    }

    if (response.status === 204) {
      return undefined as T;
    }

    return response.json() as Promise<T>;
  }

  async get<T>(path: string): Promise<T> {
    return this.request<T>('GET', path);
  }

  async post<T>(path: string, body: any): Promise<T> {
    return this.request<T>('POST', path, body);
  }

  async put<T>(path: string, body: any): Promise<T> {
    return this.request<T>('PUT', path, body);
  }

  async patch<T>(path: string, body: any): Promise<T> {
    return this.request<T>('PATCH', path, body);
  }

  async delete<T>(path: string, body?: any): Promise<T> {
    return this.request<T>('DELETE', path, body);
  }
}

let defaultClient = new HttpClient();

export function configureClient(config: ClientConfig): void {
  defaultClient = new HttpClient(config);
}

export function getClient(): HttpClient {
  return defaultClient;
}

export { HttpClient };
