// Auto-generated by generate-openapi.ts
// Do not edit manually
import { getEnvVar } from '../runtime-env.js';

export interface ClientConfig {
  apiHost?: string;
  apiKey?: string;
  getApiHost?: () => string | undefined;
  getApiKey?: () => string | undefined;
}

const defaultGetApiHost = () => getEnvVar('TIER0_API_HOST');
const defaultGetApiKey = () => getEnvVar('TIER0_API_KEY');

function normalizeBaseURL(host: string): string {
  const trimmed = host.trim().replace(/\/+$/, '');
  if (/^https?:\/\//i.test(trimmed)) {
    return trimmed;
  }
  return `http://${trimmed}`;
}

class HttpClient {
  private config: ClientConfig;

  constructor(config: ClientConfig = {}) {
    this.config = config;
  }

  private getBaseURLInternal(): string {
    const host = this.config.apiHost || this.config.getApiHost?.() || defaultGetApiHost();
    if (!host || !host.trim()) {
      throw new Error('Tier0 SDK: apiHost is required. Set it via ClientConfig or TIER0_API_HOST environment variable.');
    }
    return normalizeBaseURL(host);
  }

  private getApiKeyInternal(): string | undefined {
    return this.config.apiKey || this.config.getApiKey?.() || defaultGetApiKey();
  }

  private async request<T>(method: string, path: string, body?: any, options?: { signal?: AbortSignal }): Promise<T> {
    const baseURL = this.getBaseURLInternal();
    const url = `${baseURL}${path}`;
    const apiKey = this.getApiKeyInternal();

    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };

    if (apiKey) {
      // 网关各接口认证头不一致：多数接口认 Authorization Bearer，
      // 个别接口（如 /openapi/v1/auth/whoami）只认 X-API-Key，两个都带
      headers['Authorization'] = `Bearer ${apiKey}`;
      headers['X-API-Key'] = apiKey;
    }

    const response = await fetch(url, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
      signal: options?.signal,
    });

    if (!response.ok) {
      const text = await response.text().catch(() => 'Unknown error');
      throw new Error(`HTTP ${response.status}: ${text}`);
    }

    if (response.status === 204) {
      return undefined as T;
    }

    return response.json() as Promise<T>;
  }

  async get<T>(path: string, options?: { signal?: AbortSignal }): Promise<T> {
    return this.request<T>('GET', path, undefined, options);
  }

  async post<T>(path: string, body: any, options?: { signal?: AbortSignal }): Promise<T> {
    return this.request<T>('POST', path, body, options);
  }

  async put<T>(path: string, body: any, options?: { signal?: AbortSignal }): Promise<T> {
    return this.request<T>('PUT', path, body, options);
  }

  async patch<T>(path: string, body: any, options?: { signal?: AbortSignal }): Promise<T> {
    return this.request<T>('PATCH', path, body, options);
  }

  async delete<T>(path: string, body?: any, options?: { signal?: AbortSignal }): Promise<T> {
    return this.request<T>('DELETE', path, body, options);
  }

  /**
   * 获取当前客户端配置的 base URL（末尾不含斜杠）。
   * 供文件下载等需要直接操作完整 URL 的场景使用。
   */
  getBaseURL(): string {
    return this.getBaseURLInternal();
  }

  /**
   * 获取当前客户端配置的 API Key。
   * 供文件下载等需要手动构造请求头的场景使用。
   */
  getApiKey(): string | undefined {
    return this.getApiKeyInternal();
  }
}

let defaultClient = new HttpClient();

export function configureClient(config: ClientConfig): void {
  defaultClient = new HttpClient(config);
}

export function getClient(): HttpClient {
  return defaultClient;
}

export { HttpClient };
