/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/gw/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGwReload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/auth/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1AuthWhoami"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/flow/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1FlowCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/flow/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1FlowDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/flow/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1FlowDeploy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/flow/flowdata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1FlowFlowdata"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/flow/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1FlowGet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/flow/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1FlowList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/flow/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1FlowNodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/flow/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1FlowUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1Info"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/uns/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1UnsBrowse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/uns/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1UnsCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/uns/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1UnsDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/uns/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1UnsHistory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/uns/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1UnsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/uns/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1UnsRestore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/uns/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1UnsSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/uns/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1UnsUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/uns/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1UnsWrite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/v1/launchpad/{projectName}/getMembers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postOpenapiV1Launchpad:projectNameGetMembers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthWhoamiResp */
        AuthWhoamiResp: {
            apiKeyName: string;
            email: string;
            keyPrefix: string;
            keyType: string;
            permissions: string[];
            roles: string[];
            /** Format: int64 */
            userID: number;
            userName: string;
            /** Format: int64 */
            workspaceID: number;
            workspaceName: string;
        };
        /** BrowseReq */
        BrowseReq: {
            /** Format: boolean */
            include_leaf_value?: boolean;
            /** Format: boolean */
            include_metadata?: boolean;
            /** Format: int64 */
            max_depth?: number;
            path?: string;
        };
        /** BrowseResp */
        BrowseResp: {
            tree: components["schemas"]["OpenapiNodeInfo"][];
        };
        /** CliAuthStatusReq */
        CliAuthStatusReq: {
            setupCode: string;
        };
        /** CreateResp */
        CreateResp: {
            results: components["schemas"]["OpenapiCreateResult"][];
            /** Format: boolean */
            success: boolean;
        };
        /** FlowCreateReq */
        FlowCreateReq: {
            description?: string;
            flowName: string;
            flowType: string;
            template?: string;
        };
        /** FlowCreateResp */
        FlowCreateResp: {
            /** Format: int64 */
            id: number;
        };
        /** FlowDataResp */
        FlowDataResp: {
            flows: Record<string, never>[];
            rev: string;
        };
        /** FlowDeleteReq */
        FlowDeleteReq: {
            ids: number[];
        };
        /** FlowDeployReq */
        FlowDeployReq: {
            flowsJson: string;
            /** Format: int64 */
            id: number;
        };
        /** FlowDeployResp */
        FlowDeployResp: {
            flowId: string;
        };
        /** FlowEmptyResp */
        FlowEmptyResp: {
            /** Format: boolean */
            success: boolean;
        };
        /** FlowGetReq */
        FlowGetReq: {
            /** Format: int64 */
            id: number;
        };
        /** FlowInfo */
        FlowInfo: {
            /** Format: int64 */
            createdTime: number;
            /** Format: int64 */
            currentVersionId: number;
            currentVersionName: string;
            currentVersionType: string;
            description: string;
            flowId: string;
            flowName: string;
            flowStatus: string;
            flowType: string;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            isFavorite: number;
            template: string;
            /** Format: int64 */
            updatedTime: number;
        };
        /** FlowListReq */
        FlowListReq: {
            flowType?: string;
            keyword?: string;
        };
        /** FlowListResp */
        FlowListResp: {
            list: components["schemas"]["FlowInfo"][];
        };
        /** FlowNodesReq */
        FlowNodesReq: {
            flowType: string;
        };
        /** FlowNodesResp */
        FlowNodesResp: {
            nodes: components["schemas"]["NodeRedNodeSet"][];
        };
        /** FlowUpdateReq */
        FlowUpdateReq: {
            description?: string;
            flowName?: string;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            isFavorite?: number;
            template?: string;
        };
        /** HistoryAggregation */
        HistoryAggregation: {
            field: string;
            function: string;
            interval: string;
        };
        /** HistoryReq */
        HistoryReq: {
            aggregation?: components["schemas"]["HistoryAggregation"];
            end_time: string;
            /** Format: int64 */
            page?: number;
            /** Format: int64 */
            size?: number;
            start_time: string;
            topics: string[];
        };
        /** HistoryResp */
        HistoryResp: {
            /** Format: int64 */
            page: number;
            results: components["schemas"]["OpenapiHistoryItem"][];
            /** Format: int64 */
            size: number;
            /** Format: boolean */
            success: boolean;
            /** Format: int64 */
            total: number;
        };
        /** InfoReq */
        InfoReq: Record<string, never>;
        /** NamespaceNode */
        NamespaceNode: {
            alias?: string;
            children?: components["schemas"]["NamespaceNode"][];
            description?: string;
            displayName?: string;
            extendProperties?: {
                [key: string]: string;
            };
            fields?: components["schemas"]["SchemaField"][];
            name: string;
            topicType?: string;
            type: string;
        };
        /** NodeCreateReq */
        NodeCreateReq: {
            namespace: components["schemas"]["NamespaceNode"][];
        };
        /** NodeDeleteReq */
        NodeDeleteReq: {
            /** Format: boolean */
            hard_delete?: boolean;
            topics: string[];
        };
        /** NodeRedNodeSet */
        NodeRedNodeSet: {
            /** Format: boolean */
            enabled: boolean;
            id: string;
            module: string;
            name: string;
            types: string[];
            version: string;
        };
        /** NodeRestoreReq */
        NodeRestoreReq: {
            path: string;
        };
        /** NodeUpdateReq */
        NodeUpdateReq: {
            alias?: string;
            description?: string;
            displayName?: string;
            extendProperties?: {
                [key: string]: string;
            };
            fields?: components["schemas"]["SchemaField"][];
            name?: string;
            path: string;
            updateMask?: string[];
        };
        /** OpenapiCreateResult */
        OpenapiCreateResult: {
            error?: components["schemas"]["OpenapiItemError"];
            /** Format: boolean */
            success: boolean;
            topic: string;
        };
        /** OpenapiEmptyResp */
        OpenapiEmptyResp: {
            /** Format: boolean */
            success: boolean;
        };
        /** OpenapiHistoryItem */
        OpenapiHistoryItem: {
            error?: components["schemas"]["OpenapiItemError"];
            result?: components["schemas"]["OpenapiHistoryResult"];
            /** Format: boolean */
            success: boolean;
            topic: string;
        };
        /** OpenapiHistoryResult */
        OpenapiHistoryResult: {
            values: components["schemas"]["OpenapiHistoryValue"][];
        };
        /** OpenapiHistoryValue */
        OpenapiHistoryValue: {
            quality: string;
            /** Format: int64 */
            timeStamp: number;
            value?: Record<string, never>;
        };
        /** OpenapiItemError */
        OpenapiItemError: {
            /** Format: int64 */
            code: number;
            message: string;
        };
        /** OpenapiNodeInfo */
        OpenapiNodeInfo: {
            alias?: string;
            children?: components["schemas"]["OpenapiNodeInfo"][];
            description?: string;
            displayName?: string;
            /** Format: int64 */
            enableHistory?: number;
            extendProperties?: {
                [key: string]: string;
            };
            fields?: components["schemas"]["SchemaField"][];
            /** Format: int64 */
            id: number;
            name: string;
            path: string;
            payload?: components["schemas"]["OpenapiVQT"];
            topicType: string;
            type: string;
        };
        /** OpenapiReadItem */
        OpenapiReadItem: {
            error?: components["schemas"]["OpenapiItemError"];
            metadata?: components["schemas"]["OpenapiNodeInfo"];
            result?: components["schemas"]["OpenapiVQT"];
            /** Format: boolean */
            success: boolean;
            topic: string;
        };
        /** OpenapiVQT */
        OpenapiVQT: {
            quality: string;
            /** Format: int64 */
            timeStamp: number;
            value?: Record<string, never>;
        };
        /** OpenapiWriteResult */
        OpenapiWriteResult: {
            error?: components["schemas"]["OpenapiItemError"];
            /** Format: boolean */
            success: boolean;
            topic: string;
        };
        /** ReadReq */
        ReadReq: {
            /** Format: boolean */
            include_leaf_value?: boolean;
            /** Format: boolean */
            include_metadata?: boolean;
            topics: string[];
        };
        /** ReadResp */
        ReadResp: {
            results: components["schemas"]["OpenapiReadItem"][];
            /** Format: boolean */
            success: boolean;
        };
        /** Response */
        Response: {
            message: string;
        };
        /** SchemaField */
        SchemaField: {
            name: string;
            type: string;
            unit?: string;
        };
        /** SearchReq */
        SearchReq: {
            /** Format: boolean */
            include_leaf_value?: boolean;
            /** Format: boolean */
            include_metadata?: boolean;
            keyword?: string;
            /** Format: int64 */
            page?: number;
            path_prefix?: string;
            /** Format: int64 */
            size?: number;
            topicType?: string;
        };
        /** SearchResp */
        SearchResp: {
            objects: components["schemas"]["OpenapiNodeInfo"][];
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            size: number;
            /** Format: int64 */
            total: number;
        };
        /** WriteItem */
        WriteItem: {
            /** Format: int64 */
            timeStamp?: number;
            topic: string;
            value?: Record<string, never>;
        };
        /** WriteReq */
        WriteReq: {
            /** Format: int64 */
            qos?: number;
            /** Format: boolean */
            retain?: boolean;
            writes: components["schemas"]["WriteItem"][];
        };
        /** WriteResp */
        WriteResp: {
            results: components["schemas"]["OpenapiWriteResult"][];
            /** Format: boolean */
            success: boolean;
        };
        /** LaunchpadGetMembersReq */
        LaunchpadGetMembersReq: {
            /** Format: int64 */
            page?: number;
            roleKey?: string;
            roles?: string[];
            /** Format: int64 */
            size?: number;
            updatedAtEnd?: string;
            updatedAtStart?: string;
        };
        /** LaunchpadMembersResp */
        LaunchpadMembersResp: {
            list: components["schemas"]["LaunchpadMemberResp"][];
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            size: number;
            /** Format: int64 */
            total: number;
        };
        /** LaunchpadMemberResp */
        LaunchpadMemberResp: {
            accessLevel: string;
            email?: string;
            /** Format: int64 */
            memberId: number;
            roles: components["schemas"]["LaunchpadMemberRoleResp"][];
            updatedAt?: string;
            userId: string;
            userName?: string;
        };
        /** LaunchpadMemberRoleResp */
        LaunchpadMemberRoleResp: {
            apps?: components["schemas"]["LaunchpadMemberRoleAppResp"][];
            description?: string;
            /** Format: int64 */
            memberCount: number;
            /** Format: int64 */
            roleId: number;
            roleKey: string;
            roleName?: string;
        };
        /** LaunchpadMemberRoleAppResp */
        LaunchpadMemberRoleAppResp: {
            /** Format: int64 */
            appId: number;
            appName: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGwReload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["Response"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1AuthWhoami: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["AuthWhoamiResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1FlowCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlowCreateReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["FlowCreateResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1FlowDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlowDeleteReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["FlowEmptyResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1FlowDeploy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlowDeployReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["FlowDeployResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1FlowFlowdata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlowGetReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["FlowDataResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1FlowGet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlowGetReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["FlowInfo"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1FlowList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlowListReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["FlowListResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1FlowNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlowNodesReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["FlowNodesResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1FlowUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlowUpdateReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["FlowEmptyResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1Info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InfoReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1UnsBrowse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrowseReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["BrowseResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1UnsCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeCreateReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["CreateResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1UnsDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeDeleteReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["OpenapiEmptyResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1UnsHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["HistoryResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1UnsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["ReadResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1UnsRestore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeRestoreReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["OpenapiEmptyResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1UnsSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["SearchResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1UnsUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeUpdateReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["OpenapiEmptyResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    postOpenapiV1UnsWrite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["WriteResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
    "postOpenapiV1Launchpad:projectNameGetMembers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectName: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaunchpadGetMembersReq"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * 返回code
                         * @default 200
                         */
                        code: number;
                        data?: components["schemas"]["LaunchpadMembersResp"];
                        /** 返回的消息 */
                        msg?: string;
                    };
                };
            };
        };
    };
}
