// Auto-generated by generate-openapi.ts
// Do not edit manually

// Vue composables require vue to be installed
import { ref } from 'vue';
import { systemApi, flowApi, unsApi, launchpadApi, platformApi } from './api.js';
import type { components } from './types.js';

export function useGwreload() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async () => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await systemApi.gwreload();
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1authwhoami() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async () => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await systemApi.openapiv1authwhoami();
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1info() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["InfoReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await systemApi.openapiv1info(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1flowcreate() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["FlowCreateReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await flowApi.openapiv1flowcreate(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1flowdelete() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["FlowDeleteReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await flowApi.openapiv1flowdelete(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1flowdeploy() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["FlowDeployReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await flowApi.openapiv1flowdeploy(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1flowflowdata() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["FlowGetReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await flowApi.openapiv1flowflowdata(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1flowget() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["FlowGetReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await flowApi.openapiv1flowget(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1flowlist() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["FlowListReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await flowApi.openapiv1flowlist(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1flownodes() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["FlowNodesReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await flowApi.openapiv1flownodes(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1flowupdate() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["FlowUpdateReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await flowApi.openapiv1flowupdate(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1unsbrowse() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["BrowseReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await unsApi.openapiv1unsbrowse(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1unscreate() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["NodeCreateReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await unsApi.openapiv1unscreate(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1unsdelete() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["NodeDeleteReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await unsApi.openapiv1unsdelete(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1unshistory() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["HistoryReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await unsApi.openapiv1unshistory(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1unsread() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["ReadReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await unsApi.openapiv1unsread(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1unsrestore() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["NodeRestoreReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await unsApi.openapiv1unsrestore(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1unssearch() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["SearchReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await unsApi.openapiv1unssearch(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1unsupdate() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["NodeUpdateReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await unsApi.openapiv1unsupdate(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1unswrite() {
  const data = ref<any | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["WriteReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await unsApi.openapiv1unswrite(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1launchpadgetmembers() {
  const data = ref<{ code: number; msg?: string; data?: components["schemas"]["LaunchpadMembersResp"] } | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (params: { "projectName": string; body: components["schemas"]["LaunchpadGetMembersReq"] }) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await launchpadApi.openapiv1launchpadgetmembers(params);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

export function useOpenapiv1platformgetmembers() {
  const data = ref<{ code: number; msg?: string; data?: components["schemas"]["PlatformMembersResp"] } | null>(null);
  const loading = ref(false);
  const error = ref<Error | null>(null);

  const execute = async (body: components["schemas"]["PlatformGetMembersReq"]) => {
    loading.value = true;
    error.value = null;
    try {
      data.value = await platformApi.openapiv1platformgetmembers(body);
      return data.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  };

  return { data, loading, error, execute };
}

